name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository...
        uses: actions/checkout@v3
      - name: Run tests...
        uses: ./.github/action-test
      - name: Deploy documentation...
        if: github.event_name != 'pull_request'
        env:
          SURGE_DOMAIN: ${{ github.ref_name == 'master' && 'fcpp-doc.surge.sh' || 'fcpp-dev.surge.sh' }}
        run: npx surge './src/doc/html' "$SURGE_DOMAIN" --token ${{ secrets.SURGE_TOKEN }}
